language: java
sudo: required
jdk:
- oraclejdk8
addons:
  srcclr: true
  apt:
    packages:
    - oracle-java8-installer
cache:
  directories:
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_665a7cbb68c6_key -iv $encrypted_665a7cbb68c6_iv
  -in github_deploy_key.enc -out github_deploy_key -d
- git clone -b travis `git config --get remote.origin.url` target/travis
install: echo Install phase has been disabled as a complete build is run during deployment
script:
- mvn test jacoco:report coveralls:report --settings target/travis/settings.xml
before_cache:
- mvn site site:deploy --settings target/travis/settings.xml -DskipTests=true
- mvn deploy --settings target/travis/settings.xml -DskipTests=true -f common/pom.xml
- mvn deploy --settings target/travis/settings.xml -DskipTests=true -f client/pom.xml
- cd server
- mvn clean heroku:deploy --settings ../target/travis/settings.xml -DskipTests=true
- cd ..
after_success:
- git checkout master
- "\\curl -sSL https://get.rvm.io | bash -s stable --ruby"
- rvm reload
- gem install github_changelog_generator -v 1.13.0
- github_changelog_generator
- grep "." github_deploy_key >> ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa
- git config --global user.email $GH_USER_EMAIL
- git config --global user.name $GH_USER_NAME
- git add CHANGELOG.md
- git commit -m "[skip ci] Updated Changelog"
- git push git@github.com:vatbub/tictactoe.git master
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
deploy:
      - provider: s3
          access_key_id: "AKIAJSC2OK26PK2HI37Q"
          secret_access_key: secure: "BBFzvDE6CR8HNyNAnsjFifP8QTI3MF+QGKLWGQHsZvbmIZ3HIaU6H9xyyRVzZtWAbcYVQGEs4umALrIuicdhLtCDx9uXkdRX1cnceE0n1dvjCk5wU4HvD3rZyFluVW0w3hLd8/z1XmKS2SWD1t+e0WJavbeYRNKwsPn0EoIY7bXLbkz0l5obdMFJegj9Fp8J7zbkrxZr5CIgyzAUiDNJwWK9xEyfcAFmd1yp5fhKO9Cj8cxTr8Er7P/AW2Tt8sPFRJuqNgQbtCfHsd9ZglHxMiCb+UXF2ehvM2Z/4w2Iaexh6oKt+yOWTgiR1uW6P2pSkhVTyC2WsKf+u/sIAB5LDrfF8/JsYxN3jy/Nx/ruOlXCbyZIamxV5PlYvjQmI/pAsrWRID2jToGnw10HWcvRnTtKkv5b4fTehZ2Heq55D/ItBErTqo2qqjPUZq/6mZ70iuc0HSpqYygQSCSTxFLjitWhE9lv4DWVe3EvrzXKwu1JGG9u0y8NIey35ESumomy4vhW5fiACNUQPLj2iMF7qdT511T+I/aKlIcUR5vohcTRk+hVwWHxt/6fJ7NESdvqvIZAu9hpUrfHUkeMGQl6CM0xEpi2eaD+tiOM8YeJABV2Ql7FcPYrFIDxl9S6SAeTaBeZUNUz+/3M0bHUoWxItNDxbaMMga/0cetQJCu/AN8="
          bucket: "vatbubtictactoeserver"
      - provider: codedeploy
          access_key_id: "AKIAJSC2OK26PK2HI37Q"
          secret_access_key: secure: "BBFzvDE6CR8HNyNAnsjFifP8QTI3MF+QGKLWGQHsZvbmIZ3HIaU6H9xyyRVzZtWAbcYVQGEs4umALrIuicdhLtCDx9uXkdRX1cnceE0n1dvjCk5wU4HvD3rZyFluVW0w3hLd8/z1XmKS2SWD1t+e0WJavbeYRNKwsPn0EoIY7bXLbkz0l5obdMFJegj9Fp8J7zbkrxZr5CIgyzAUiDNJwWK9xEyfcAFmd1yp5fhKO9Cj8cxTr8Er7P/AW2Tt8sPFRJuqNgQbtCfHsd9ZglHxMiCb+UXF2ehvM2Z/4w2Iaexh6oKt+yOWTgiR1uW6P2pSkhVTyC2WsKf+u/sIAB5LDrfF8/JsYxN3jy/Nx/ruOlXCbyZIamxV5PlYvjQmI/pAsrWRID2jToGnw10HWcvRnTtKkv5b4fTehZ2Heq55D/ItBErTqo2qqjPUZq/6mZ70iuc0HSpqYygQSCSTxFLjitWhE9lv4DWVe3EvrzXKwu1JGG9u0y8NIey35ESumomy4vhW5fiACNUQPLj2iMF7qdT511T+I/aKlIcUR5vohcTRk+hVwWHxt/6fJ7NESdvqvIZAu9hpUrfHUkeMGQl6CM0xEpi2eaD+tiOM8YeJABV2Ql7FcPYrFIDxl9S6SAeTaBeZUNUz+/3M0bHUoWxItNDxbaMMga/0cetQJCu/AN8="
          bucket: "vatbubtictactoeserver"
          key: server/target/tictactoe-server-jar-with-dependencies.jar
          application: vatbubtictactoeserver
          deployment_group: vatbubtictactoeserverDeploymentGroup
env:
  global:
  - secure: m3dsGi+8WnjVKznMbMsDKO5Pdb7N1mXVjmSBgKegBbPZog8Ds9RDiuIYF3trkkiY/O3G7A0fTaHcpbicLDl7qZLtXu9vaIiximOaT1ay/Kx0oFd8xFOMhlWbziikPRrUMe/PzMnvlvBe5x7dZZb5to/BpUT6gUBzsCcqza76T7ZEVJw9bjKmD6AvMh6deGvznpQzoHjSSs6l78YK47kky2kWJPQxbii/87nWCAgUs02ItlPunCVFi6ALdZnf1K/TAt6yzmM3opIZP8wa2EYpSqSbKzcC2T35rZMCqNbWZxALisb8UGJOUElWSjSfjqGtTdTUoZhx3fjw9PJHvXaPLfjQH9ou2cUN4mX2bi3zgdSWJOB1+k4QTPPZBoxUzw+mnX6kfGM7uLX4/g3WqSOcu+8BXoO8FbR9GQtt/SqhmgNZ0x+aQd2w04UXWZOye2cKNSVBW8YeEPn+vy269flCI3K6UsqPe7ghLmVir+gc6NJaVTp4v5fsJ4Fi/l5Smsg+44r+OyaTE96rpZ0rKJL697bcGx6A56fe04pEaDixerI2WIslM2LnsL3Vy2yIEKjaKzrm5qQZRtrGOeoJ5mFQXOvoDDqbVPnKWdffxucn1poDvEU1NQAXYFoFHyjCVUkx1XBtF4AN4/SIoL5Xk+AEwN9b0xKn7GUMXHrBVdcaZzY=
  - secure: WMTlSkzyiXS/swVc4G8I5vZnTxMv03CLLB/Uj0YkpfzWubgX5O5hupi7MxyPAWj4m1wfWuD1tfrUXW5E/28PLwnUvhEoUlbVaP4xpCE08vpPyOuJ158jYan0ZLX+tfi5XkFnW3JpQNw36oPYHc+zdHt/yWFTjmjuJg7Fu/oXWckeXLzObaE1BfOgkZDhHSm4dhJxMFmYMLvDVJbT3ZJ72++m1e3hOwtSVAPlyD1FEXuGM5tauU8IB963TXWhxdkHKzy6H5nMbPm9dC5exmsqCVe8aOVjmt+Oe9Tq8mgt0LRJldgKh/sUAbIwmt2IYc1SB+RdaHhtRRWfH9O/QruTS7YDATEBkosqKMb0OLpCOLbk9+MS0VwVkEQ6BPgnPQ02KABa3bdR7wqveWxiK7RmhrYtCGJx/jUrqSHMa6tDPnejExFOPR8gBAdvxwBRJhL8113bz1kLHjaXuzc1Eq24fac8ffzmjb97dUN7mbdW1lE73TwRL7iR0ayM9wRtUm0BuuXlAdxCIOSRLn4rvt8lOLFjLP+fKZtJk1lyITTjEieUvVo3EHwFl+lZXGu2Ajva5UBIJoNOrLhh48eyE1g4kl0IVyu1rDg+t6KGzNiEdPYOMZSiaYIg8/1C6JVhHxKez0+iAMeX40H4gedcDLGRMzMURxl3GM6JfDHaRtMxigY=
  - secure: Ze3HozNCN6LzA4wF5IrOaVAMaaZtDnqAho0NCN+fSehbNOTHc3at+omGkPD0GY34PHBReDbzmPiBQbPFSz97vdb/YfRVOBMDKNmXjS+aaMW2qysADIYVajkUbTQZagbCvrQacun8jgd2PnncA0OYxGn5TNR47oQM0TLYjbd8EqJZcXQSvxzo4Ao/OZ9uWqDXo8hwD2QvBrAZF/ibKRS9JDTDnCQJRCd5Hths5leVYoJOdN8gCCOirEnqIdvpLAxJO7ZAh/HkbXzMQS0GgCnl1ZHVb6vneq+j2G+qHepcf9L8OoAeCH1OrbcNMaLMoMbXrl3stHYC9oyg0fx4QBKHUlohpTjZy1TZy24HeZcOBcEEjBQQN7KLXGpyDHEedlwD5SHYA4z86JgDVyD/SfrbPJMgvNFhShqdBzdh9+s8qSVz5/9Uf5XWWXFGCm/MNcJaeznPYrtTJpd4e3AVgzgW3EdDZ1k2nmZ426mkm/1YCaq9+HTsM5z7f0vh8b8np4JGFyET5lP03Z47HXfdrPuq4doBb1dSiXYPGTKHxEFsNdo4xeF+lcYFmz0yqT2vBhGrH+Y+2Bp30YXVmzyonYO6bSyUsxYt0V2D/E0t4YmGVLtatG5Nr8hj1XsKcHtbqezm3Z3PoEjiQuMjVKLJtQ3HJ0ZUJsgJkjG6EcxmjSUaUBM=
  - secure: mEStNITTT7yvtM2RWNjC+KFz3mF1OGuI5Fz7UmAkOoC24QZ+yw9VqqhpM8GvIWw9zqOK83kPtXe9NhGDIm/2PshgStaT/XURCy4FLXrX2cYWsP61M49h/fBQhmjjwwYCbdqV9goOBCM19133CBFTU4r3Xmj3R7fj13E94Z2oZFqxWkKwTCEW+n5EehThq8ALOikpCj0EEXbSmn8xpVm/nXV6BjqeyBzOPY5eEv+81zy+ws7LBkiUtJkeymIu0JF7JdWaR72hju41NMddoU/Z4HdabFAT8npDFHL8fXodft42vPtV8G1gF4eOVcXb6vmES5X0FPDEHhVyllV1QjfW5NS7QIUKC1iNecV8zCZYfeQrho3QwwIpwKzzMXeNxj2ofvApSNoV7xveQ8Av0UyvYdRsxIMGURCUc4HbMG2H4EyQmMPA3HF5r5l9Y7Xx0cR99AKkLR63ZlDr/bOw9sVv4xiUs9nYaGqzBOyHmtxye8+SVb65tM1e49vMcpaCAKUjqMVEBZd5jcW15gU/QcBp9I2cNhQj0TdhXpYtAVZGFZAkXES0xum67C9Cn/8AkNtO6ibGFLWdzbUHv16tltqhRxV8oKRhQoLMTecqr+7zx50mrXWTBR2wrb51PhBeTNvD4EJFVSdONBG7dah0JtQO7XWHt7i/rGk5OuVzIdRgL5g=
  - secure: kSdBCzQM8Yedpiguj90Laz2UYx1F1rvcckFhuNBtWsQHQb1WFG7G54zaZzFt7bN67BePuEtgSPZ914Zlg8MG6Grm0v/HxoT8hms5YPekDpOtISC/NybXpy4EA6tOdf3fLI/jVm0iPwydC2V5y9Wrl2JNqQTPvsqhcKdIxT+hkwCm3qhAv7TO7/nU/OnAFifFx3w9LiIZvddEqyk4VnDTowK2+gNq16LsZdS+sjKHMO/5+9Aj51lH1VkLbbMp1W0dgk3MTBpIhEggfYi5/zazlQ7c600UrKUYxsP1fAC9o91nkGeXBmL57TWXjt3ZmO9rW2MOkLAL8qzo6GCnQJfyEU8N6rZ/sIs5gmwJ5Wvt0mZOFjwTpQJ7e71EEjCblyvTXMhit8f+6GUGyxgwM2dF0iKpzTTK0+in27RaGUiqJf9Lrqqj12OhCd6kNDtgEbQRGA1nTqk0KPCNYQeW93ew4EgTlaIRMBp1gU82MjkG8VCEVhMqlUWVTPdLWKNLByrzKiq9wjgTvoTQQQRYEp3rFhRI8cHHYcg+RQ3M6ucXuBie2fsoLGkeUgyXkhwexVB13E0igZSLUPi0Wf6iF1zrU9tPJsTtvnjy8GjCmCmTxPDdLs+c+O5i/CpFFE9mG8OwOtISmfIVoz8H0ghypR/b++Gss19ct/c1Mzxo/NMDJWo=
  - secure: PyFhpxev9c+XsC3MCSn0E/PiVYkUvblhR27vJMdzk2aq+k93plenEWPPm+w7C9UTkjXucLN+7/JplX5ohwvE1rUIifpGu+N/4ItGIq7fJp3eKFO6QFdG2KNDzLJ0QvJwX3nF1Jh+88sJonifL0cs5dHRuTxfu2CC64xwNJtYOCA5dKwzLzHsWCwLJ0/fYd3XgFcgVejxBKlZciGfzpK7beGnDowBKRDeEV17grtapHyQ6qO47hkAFOi6+k7YWh+rg7w/xBK7RDR2KxzEeJIC37hQQKTenjSpprmF3rJEF82TKU7ELf17SWze8xW1V6sQiVHhr71FCMrojeUHiL5g2pZGWNfSOwc8EjfePj7SQ/DHnwJUYvk/Nv+gGwHJMqSl7r6mhBhKOvJVrwLpFRQfoEo9NK708ULIUVTKBtOZjYdHGLMFXFSVjCto/9Q9SCv8o2IOVbzXzXMPpHJCRzl4XOnr/WiP+CRqVfoJFoHI1LOC52NUbxvsHVHlSPy5Wqqg26DhhKuPL1nVDi9dBLv7mUVOgEDHT5aPHfIe1aGS+syv6piYfIO2l4Bv5ah1WvX/BE/wxikbNYS8mXz6i1hIIQzWt8N5+RFb3vo9AJco1zK3x9hLnmI9w2cjlh8xr4eg24BlIhGJ7/2SSSscqXKuv4qcSUvHCiCT9OMHlpbcFDA=
  - secure: vYofRmYFSFHrTpzqXLpDt/K779SVx47iPTzUNCiH+X2ZSNzANu58uDYgGkoz/iKdC+DGhPVrrgMmij9nVDPJ2oYAigVUZmmyunnL9DmBOU6EagC50brm1CSwCAxgq30RsgnSbF6nWMgVoo8FR6tPsMeaRSXNfgiR0VNt0+mR5+JcFt0Wwj0gSVBfqokkX6awPwkBqpk4mMcqbpS5sx8v6G7DrtKTL4bauPHTS6iQC1TbdWnSy/F/kwAllGdzsGp3zcDzzNWuS+h22sdSQohVeUnlkBlKTJRFDoVp4RNynIyz4m7+i35AXz2UQpGolijJ2Jc2UkXm/9m6d758b7FvMdq2SqPeFoD3EBIcS8SVP+ju8tl3bqNnrl8WZxWsd1e+KIlsI0DLUmsAVv5RGnjz3sPTipQ5kZpmin5f/qEFHZ0770fw17zBaiGwDARjJ5DpCOolP2cfV3GOPFrmeqxb3IR0yOTyKzjbAQkOLU56q47CxSmoMrA4Su0z/lj+5MzT3u7TKWAEs4vDka90MUxm9dHcNfCUWNScoVsLBBlcbu2G4F8oIgbURffikPhkw1hyVAp4ejia2bv+HpoFG9jfsYDq05T6l7n55tdaG/MVLjlABW9zKJpLpc9ZXNNIVirKL2jJ0UxOBzwR7jktFNhbr0CffKfJTMunH2wK498Bj98=
